CREATE TABLE IF NOT EXISTS accounts (
  id UUID PRIMARY KEY,
  owner TEXT NOT NULL,
  balance NUMERIC(19,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version BIGINT NOT NULL DEFAULT 0
);