version: "3.9"

services:
  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_NGINX_HTTP_INCLUDE: /usr/local/kong/nginx-http.conf
    ports:
      - "8000:8000"  # Public gateway
      - "8001:8001"  # Admin
    volumes:
      - ../kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
      - ../kong/kong-nginx-http.conf:/usr/local/kong/nginx-http.conf:ro
    depends_on: [bff, frontend]
    networks: [appnet]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev","--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ../realms:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks: [appnet]

  redis:
    image: redis:7
    networks: [appnet]

  bff:
    build: ../bff
    environment:
      OIDC_CLIENT_SECRET: CHANGE_ME   # demo-realm.json の secret と一致させる
    expose: ["8080"]
    depends_on: [keycloak, redis, savings-service, time-deposit-service]
    networks: [appnet]

  frontend:
    build: ../frontend
    expose: ["5173"]
    networks: [appnet]

  savings-service:
    build: ../savings-service
    expose: ["8081"]
    networks: [appnet]

  time-deposit-service:
    build: ../time-deposit-service
    expose: ["8082"]
    networks: [appnet]

networks:
  appnet:
    driver: bridge
